name: Scrape latest data

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch data
      run: |-
        curl curl https://apps.skyharbor.com/flightinformation | jq . > data.json
        cp data.json daily/$(TZ=America/Phoenix date +%F).json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(TZ=America/Phoenix date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push